name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        run: |
          pwd
          ls -la

      - name: Verify requirements.txt exists
        run: |
          test -f requirements.txt && echo "requirements.txt found" || (echo "requirements.txt NOT found"; exit 1)

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests (with coverage)
        run: python -m pytest -q --cov=./ --cov-report=term --cov-report=xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  docker-test:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test inside container
        run: |
          IMAGE=aceest-fitness:${{ github.sha }}
          docker build -t "$IMAGE" .
          docker run --rm -e PYTHONPATH=/app "$IMAGE" python -m pytest -q
